--------------------------------------------------------
--  已建立檔案 - 星期二-十一月-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ARTID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "ARTID_SEQUENCE"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 41 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence COMID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "COMID_SEQUENCE"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 121 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table F_ARTICLE
--------------------------------------------------------

  CREATE TABLE "F_ARTICLE" 
   (	"ART_CONTENT" CLOB, 
	"ART_CRE_TIME" DATE, 
	"ART_USERID" VARCHAR2(255 BYTE), 
	"ART_COMM_NUM" NUMBER(*,0), 
	"ART_VIEW" NUMBER(*,0), 
	"ART_ID" NUMBER(*,0), 
	"ART_TYPE_ID" NUMBER, 
	"ART_TITLE" VARCHAR2(255 BYTE), 
	"ART_PIC" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ART_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ART_PIC") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "F_ARTICLE"."ART_CRE_TIME" IS '建立時間';
   COMMENT ON COLUMN "F_ARTICLE"."ART_COMM_NUM" IS '評論數';
   COMMENT ON COLUMN "F_ARTICLE"."ART_VIEW" IS '文章觀看數';
   COMMENT ON COLUMN "F_ARTICLE"."ART_TYPE_ID" IS '文章分類';
--------------------------------------------------------
--  DDL for Table F_ART_TYPE
--------------------------------------------------------

  CREATE TABLE "F_ART_TYPE" 
   (	"TYPE_ID" NUMBER(*,0), 
	"TYPE_NAME" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table F_COMMENT
--------------------------------------------------------

  CREATE TABLE "F_COMMENT" 
   (	"COM_ID" NUMBER, 
	"COM_CONTENT" VARCHAR2(255 BYTE), 
	"COM_ART_ID" NUMBER, 
	"COM_USER_ID" VARCHAR2(255 BYTE), 
	"COM_DATE" DATE, 
	"COM_PIC" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("COM_PIC") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table F_MULTI_COM
--------------------------------------------------------

  CREATE TABLE "F_MULTI_COM" 
   (	"MULTI_COM_COM_ID" NUMBER, 
	"MULTI_COM_USER_ID" VARCHAR2(255 BYTE), 
	"MULTI_COM_DATE" TIMESTAMP (6), 
	"MULTI_COM_CONTENT" VARCHAR2(255 BYTE), 
	"MULTI_COM_PIC" BLOB, 
	"MULTI_COM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("MULTI_COM_PIC") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Trigger COMMENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COMMENT_TRIGGER" 
   before insert on "F_COMMENT" 
   for each row 
begin  
   if inserting then 
      if :NEW."COM_ID" is null then 
         select COMID_SEQUENCE.nextval into :NEW."COM_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "COMMENT_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ART_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ART_ID_TRIGGER" 
   before insert on "F_ARTICLE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ART_ID" is null then 
         select ARTID_SEQUENCE.nextval into :NEW."ART_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "ART_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ART_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ART_ID_TRIGGER" 
   before insert on "F_ARTICLE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ART_ID" is null then 
         select ARTID_SEQUENCE.nextval into :NEW."ART_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "ART_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COMMENT_TRIGGER" 
   before insert on "F_COMMENT" 
   for each row 
begin  
   if inserting then 
      if :NEW."COM_ID" is null then 
         select COMID_SEQUENCE.nextval into :NEW."COM_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "COMMENT_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table F_ARTICLE
--------------------------------------------------------

  ALTER TABLE "F_ARTICLE" MODIFY ("ART_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" MODIFY ("ART_CRE_TIME" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" MODIFY ("ART_USERID" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" MODIFY ("ART_ID" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" MODIFY ("ART_TITLE" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" ADD CONSTRAINT "ARTICLE_PK" PRIMARY KEY ("ART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_ART_TYPE
--------------------------------------------------------

  ALTER TABLE "F_ART_TYPE" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "F_ART_TYPE" MODIFY ("TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "F_ART_TYPE" ADD CONSTRAINT "F_ART_TYPE_PK" PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_COMMENT
--------------------------------------------------------

  ALTER TABLE "F_COMMENT" MODIFY ("COM_ART_ID" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" MODIFY ("COM_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" MODIFY ("COM_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" MODIFY ("COM_DATE" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" ADD CONSTRAINT "F_COMMENT_PK" PRIMARY KEY ("COM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_MULTI_COM
--------------------------------------------------------

  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_ID" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_COM_ID" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_DATE" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" ADD CONSTRAINT "F_MULTI_COM_PK" PRIMARY KEY ("MULTI_COM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_ARTICLE
--------------------------------------------------------

  ALTER TABLE "F_ARTICLE" ADD CONSTRAINT "TYPE_ID" FOREIGN KEY ("ART_TYPE_ID")
	  REFERENCES "F_ART_TYPE" ("TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_COMMENT
--------------------------------------------------------

  ALTER TABLE "F_COMMENT" ADD CONSTRAINT "ART_ID" FOREIGN KEY ("COM_ART_ID")
	  REFERENCES "F_ARTICLE" ("ART_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_MULTI_COM
--------------------------------------------------------

  ALTER TABLE "F_MULTI_COM" ADD CONSTRAINT "FK_MULTI_COM" FOREIGN KEY ("MULTI_COM_COM_ID")
	  REFERENCES "F_COMMENT" ("COM_ID") ENABLE;
