--------------------------------------------------------
--  已建立檔案 - 星期三-十一月-04-2020   
--------------------------------------------------------
DROP SEQUENCE "ARTID_SEQUENCE";
DROP SEQUENCE "COMID_SEQUENCE";
DROP SEQUENCE "ISEQ$$_78365";
DROP TABLE "F_ARTICLE";
DROP TABLE "F_ART_TYPE";
DROP TABLE "F_COMMENT";
DROP TABLE "F_MULTI_COM";
--------------------------------------------------------
--  DDL for Sequence ARTID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "ARTID_SEQUENCE"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 41 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence COMID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "COMID_SEQUENCE"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 121 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table F_ARTICLE
--------------------------------------------------------

  CREATE TABLE "F_ARTICLE" 
   (	"ART_CONTENT" CLOB, 
	"ART_CRE_TIME" DATE, 
	"ART_USERID" VARCHAR2(255 BYTE), 
	"ART_COMM_NUM" NUMBER(*,0), 
	"ART_VIEW" NUMBER(*,0), 
	"ART_ID" NUMBER(*,0), 
	"ART_TYPE_ID" NUMBER, 
	"ART_TITLE" VARCHAR2(255 BYTE), 
	"ART_PIC" BLOB, 
	"ART_PIC_URL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ART_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ART_PIC") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "F_ARTICLE"."ART_CRE_TIME" IS '建立時間';
   COMMENT ON COLUMN "F_ARTICLE"."ART_COMM_NUM" IS '評論數';
   COMMENT ON COLUMN "F_ARTICLE"."ART_VIEW" IS '文章觀看數';
   COMMENT ON COLUMN "F_ARTICLE"."ART_TYPE_ID" IS '文章分類';
--------------------------------------------------------
--  DDL for Table F_ART_TYPE
--------------------------------------------------------

  CREATE TABLE "F_ART_TYPE" 
   (	"TYPE_ID" NUMBER(*,0), 
	"TYPE_NAME" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table F_COMMENT
--------------------------------------------------------

  CREATE TABLE "F_COMMENT" 
   (	"COM_ID" NUMBER, 
	"COM_CONTENT" VARCHAR2(255 BYTE), 
	"COM_ART_ID" NUMBER, 
	"COM_USER_ID" VARCHAR2(255 BYTE), 
	"COM_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table F_MULTI_COM
--------------------------------------------------------

  CREATE TABLE "F_MULTI_COM" 
   (	"MULTI_COM_COM_ID" NUMBER, 
	"MULTI_COM_USER_ID" VARCHAR2(255 BYTE), 
	"MULTI_COM_DATE" TIMESTAMP (6), 
	"MULTI_COM_CONTENT" VARCHAR2(255 BYTE), 
	"MULTI_COM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into F_ARTICLE
SET DEFINE OFF;
Insert into F_ARTICLE (ART_CRE_TIME,ART_USERID,ART_COMM_NUM,ART_VIEW,ART_ID,ART_TYPE_ID,ART_TITLE,ART_PIC_URL) values (to_date('06-10月-20','DD-MON-RR'),'azaz4498',3,2,1,2,'花東四天三夜家庭旅行',null);
Insert into F_ARTICLE (ART_CRE_TIME,ART_USERID,ART_COMM_NUM,ART_VIEW,ART_ID,ART_TYPE_ID,ART_TITLE,ART_PIC_URL) values (to_date('05-10月-20','DD-MON-RR'),'abc123',4,2,2,3,'東北角吃海鮮、看海景好去處，推薦小漁村海產店',null);
REM INSERTING into F_ART_TYPE
SET DEFINE OFF;
Insert into F_ART_TYPE (TYPE_ID,TYPE_NAME) values (1,'旅遊');
Insert into F_ART_TYPE (TYPE_ID,TYPE_NAME) values (2,'住宿');
Insert into F_ART_TYPE (TYPE_ID,TYPE_NAME) values (3,'美食');
Insert into F_ART_TYPE (TYPE_ID,TYPE_NAME) values (4,'景點');
REM INSERTING into F_COMMENT
SET DEFINE OFF;
Insert into F_COMMENT (COM_ID,COM_CONTENT,COM_ART_ID,COM_USER_ID,COM_DATE) values (81,'哈囉',2,'azaz4498',to_date('12-10月-20','DD-MON-RR'));
Insert into F_COMMENT (COM_ID,COM_CONTENT,COM_ART_ID,COM_USER_ID,COM_DATE) values (82,'你好',1,'azaz4498',to_date('12-10月-20','DD-MON-RR'));
Insert into F_COMMENT (COM_ID,COM_CONTENT,COM_ART_ID,COM_USER_ID,COM_DATE) values (71,'很棒',2,'azaz4498',to_date('12-10月-20','DD-MON-RR'));
Insert into F_COMMENT (COM_ID,COM_CONTENT,COM_ART_ID,COM_USER_ID,COM_DATE) values (1,'謝謝分享',2,'ccc123',to_date('05-10月-20','DD-MON-RR'));
Insert into F_COMMENT (COM_ID,COM_CONTENT,COM_ART_ID,COM_USER_ID,COM_DATE) values (2,'好像很好玩嘛',2,'love123',to_date('05-10月-20','DD-MON-RR'));
Insert into F_COMMENT (COM_ID,COM_CONTENT,COM_ART_ID,COM_USER_ID,COM_DATE) values (3,'讚讚讚',1,'abc123',to_date('05-10月-20','DD-MON-RR'));
Insert into F_COMMENT (COM_ID,COM_CONTENT,COM_ART_ID,COM_USER_ID,COM_DATE) values (4,'嘿嘿嘿',1,'zxc4498',to_date('28-9月 -20','DD-MON-RR'));
REM INSERTING into F_MULTI_COM
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_PK" ON "ACCOUNT" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARTICLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARTICLE_PK" ON "F_ARTICLE" ("ART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index F_ART_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_ART_TYPE_PK" ON "F_ART_TYPE" ("TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index F_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_COMMENT_PK" ON "F_COMMENT" ("COM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index F_MULTI_COM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_MULTI_COM_PK" ON "F_MULTI_COM" ("MULTI_COM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDENTITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDENTITY_PK" ON "IDENTITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000076518C00001$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_IL0000076518C00001$$" ON "F_ARTICLE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000076518C00009$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_IL0000076518C00009$$" ON "F_ARTICLE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000077082C00005$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_IL0000077082C00005$$" ON "ACCOUNT" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index ARTICLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARTICLE_PK" ON "F_ARTICLE" ("ART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index F_ART_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_ART_TYPE_PK" ON "F_ART_TYPE" ("TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index F_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_COMMENT_PK" ON "F_COMMENT" ("COM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index F_MULTI_COM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_MULTI_COM_PK" ON "F_MULTI_COM" ("MULTI_COM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ART_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ART_ID_TRIGGER" 
   before insert on "F_ARTICLE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ART_ID" is null then 
         select ARTID_SEQUENCE.nextval into :NEW."ART_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "ART_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COMMENT_TRIGGER" 
   before insert on "F_COMMENT" 
   for each row 
begin  
   if inserting then 
      if :NEW."COM_ID" is null then 
         select COMID_SEQUENCE.nextval into :NEW."COM_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "COMMENT_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ART_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ART_ID_TRIGGER" 
   before insert on "F_ARTICLE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ART_ID" is null then 
         select ARTID_SEQUENCE.nextval into :NEW."ART_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "ART_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COMMENT_TRIGGER" 
   before insert on "F_COMMENT" 
   for each row 
begin  
   if inserting then 
      if :NEW."COM_ID" is null then 
         select COMID_SEQUENCE.nextval into :NEW."COM_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "COMMENT_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table F_ARTICLE
--------------------------------------------------------

  ALTER TABLE "F_ARTICLE" MODIFY ("ART_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" MODIFY ("ART_CRE_TIME" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" MODIFY ("ART_USERID" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" MODIFY ("ART_ID" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" MODIFY ("ART_TITLE" NOT NULL ENABLE);
  ALTER TABLE "F_ARTICLE" ADD CONSTRAINT "ARTICLE_PK" PRIMARY KEY ("ART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_ART_TYPE
--------------------------------------------------------

  ALTER TABLE "F_ART_TYPE" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "F_ART_TYPE" MODIFY ("TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "F_ART_TYPE" ADD CONSTRAINT "F_ART_TYPE_PK" PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_COMMENT
--------------------------------------------------------

  ALTER TABLE "F_COMMENT" MODIFY ("COM_ART_ID" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" MODIFY ("COM_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" MODIFY ("COM_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" MODIFY ("COM_DATE" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "F_COMMENT" ADD CONSTRAINT "F_COMMENT_PK" PRIMARY KEY ("COM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_MULTI_COM
--------------------------------------------------------

  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_ID" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_COM_ID" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_DATE" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" MODIFY ("MULTI_COM_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "F_MULTI_COM" ADD CONSTRAINT "F_MULTI_COM_PK" PRIMARY KEY ("MULTI_COM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_ARTICLE
--------------------------------------------------------

  ALTER TABLE "F_ARTICLE" ADD CONSTRAINT "TYPE_ID" FOREIGN KEY ("ART_TYPE_ID")
	  REFERENCES "F_ART_TYPE" ("TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_COMMENT
--------------------------------------------------------

  ALTER TABLE "F_COMMENT" ADD CONSTRAINT "ART_ID" FOREIGN KEY ("COM_ART_ID")
	  REFERENCES "F_ARTICLE" ("ART_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_MULTI_COM
--------------------------------------------------------

  ALTER TABLE "F_MULTI_COM" ADD CONSTRAINT "FK_MULTI_COM" FOREIGN KEY ("MULTI_COM_COM_ID")
	  REFERENCES "F_COMMENT" ("COM_ID") ENABLE;