--------------------------------------------------------
--  已建立檔案 - 星期一-十一月-09-2020   
--------------------------------------------------------
DROP TABLE "III_TEAM_DBA"."REGION" cascade constraints;
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "III_TEAM_DBA"."REGION" 
   (	"REGION_ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REGION_NAME" VARCHAR2(255 BYTE), 
	"AREA" VARCHAR2(255 BYTE)
   ) ;
REM INSERTING into III_TEAM_DBA.REGION
SET DEFINE OFF;
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (1,'基隆市','Northern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (2,'新北市','Northern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (3,'臺北市','Northern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (4,'桃園市','Northern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (5,'新竹市','Northern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (6,'新竹縣','Northern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (7,'苗栗縣','Northern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (8,'宜蘭縣','Northern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (9,'臺中市','Central');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (10,'彰化縣','Central');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (11,'南投縣','Central');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (12,'雲林縣','Central');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (13,'嘉義市','Southern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (14,'嘉義縣','Southern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (15,'臺南市','Southern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (16,'高雄市','Southern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (17,'屏東縣','Southern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (18,'花蓮縣','Eastern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (19,'臺東縣','Eastern');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (20,'澎湖縣','Outer');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (21,'金門縣','Outer');
Insert into III_TEAM_DBA.REGION (REGION_ID,REGION_NAME,AREA) values (22,'連江縣','Outer');
--------------------------------------------------------
--  DDL for Index REGION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "III_TEAM_DBA"."REGION_PK" ON "III_TEAM_DBA"."REGION" ("REGION_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "III_TEAM_DBA"."REGION" MODIFY ("REGION_ID" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."REGION" ADD CONSTRAINT "REGION_PK" PRIMARY KEY ("REGION_ID")
  USING INDEX  ENABLE;
